Stravaix/Controllers/SufferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Stravaix.Controllers
{
    using System.Collections;
    using System.Data.Entity.Migrations;
    using System.Threading.Tasks;

    using Microsoft.Ajax.Utilities;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using Microsoft.AspNet.Identity.Owin;

    using Stravaix.Models;
    using Stravaix.StravaApi.Activities;
    using Stravaix.StravaApi.Athletes;
    using Stravaix.StravaApi.Authentication;
    using Stravaix.StravaApi.Clients;
    using Stravaix.StravaApi.Streams;

    public class SufferController : Controller
    {
        private StravaixContext db = new StravaixContext();

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> About()
        {
            ViewBag.Message = "Your application description page.";

            //Task<List<Comment>> b = StravaTest();
            //List<Comment> c = b.Result;

            var b = getAthleteSummary();

            return View(b);
        }

        public JsonResult GetJsonResult()
        {
            var b = getAthleteSummary();
            return Json(b, JsonRequestBehavior.AllowGet);
        }

        public void InsertSummary(ActivitySummary summary)
        {
            //db.ActivityMetas.up AddOrUpdate(summary);
            db.ActivitySummaries.AddOrUpdate(summary);
            db.SaveChanges();

        }

        public void InsertSuffer(SufferScore scores)
        {
            db.SufferScores.AddOrUpdate(scores);
            db.SaveChanges();

        }

        private IEnumerable<SufferScore> getAthleteSummary()
        {
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            StaticAuthentication auth = new StaticAuthentication(user.StravaKey);
            //StaticAuthentication auth = new StaticAuthentication("72da1a028657d1d0a5c628c87373bebdf15151db");

            // bb636aa7c25ee744f9c961ef3e7979ed56adaee2 martin
            // 72da1a028657d1d0a5c628c87373bebdf15151db richard

            StravaClient client = new StravaClient(auth);
            StreamClient stream = new StreamClient(auth);
            List<SufferScore> stats = new List<SufferScore>();

            int ftp = 0;

            if (User.Identity.Name == "martin@hoff.no")
            {
                ftp = 370;
            }
            else
            {
                ftp = 300;
            }

            List<ActivitySummary> listAkt = client.Activities.GetActivitiesAfter(DateTime.Now.AddDays(-35));
            int i = 0;
            foreach (var actSum in listAkt)
            {
                //if (actSum.Type == ActivityType.Ride)
                //{
                    //this.InsertSummary(actSum);
                    SufferScore score = new SufferScore();
                    List<ActivityZone> actSoner = client.Activities.GetActivityZones(actSum.Id.ToString());
                    
                    double tssPulsTall = 0;
                    foreach (var zone in actSoner)
                    {
                        if (zone.Type == "heartrate")
                        {
                            if (zone.Score == null)
                            {
                                score.Score = 0;
                            }
                            else
                            {
                                score.Score = (int)zone.Score;    
                            }
                            
                            int sone = 0;
                            
                            foreach (var buckets in zone.Buckets)
                            {
                                sone++;
                                tssPulsTall += (sone * 25) * (buckets.Time / (double)3600);
                                //if (buckets.Minimum <= actSum.AverageHeartrate
                                //    && buckets.Maximum >= actSum.AverageHeartrate)
                                //{
                                    
                                //}
                                //var o = buckets.Minimum;
                            }
                        }
                    }
                    //var puls = actSoner.First();
                    var p = 1;
                    //var suffer = puls.y;
                    i += 1;
                    //DateTime dt = Convert.ToDateTime(actSum.StartDate);
                    score.Dato = actSum.StartDate;
                    //score.Dato = EpochTimeExtensions.ToEpochTime(dt) * 1000;
                    //if (puls.Score == null)
                    //{
                    //    score.Score = 0;
                    //}

                    //else
                    //{
                    //    score.Score = (int)puls.Score;
                    //}
                //switch (@enum)
                //{
                        
                //} 

                    double d = (actSum.MovingTimeSpan.TotalSeconds * actSum.WeightedAverageWatts * (actSum.WeightedAverageWatts / (double)ftp)) / (ftp * (double)3600) * 100;
                    score.TssWatt = (int)d;
                
                    
                    //double tssPuls = (70/(double)3600 * actSum.MovingTimeSpan.TotalSeconds) * 1.07;
                    score.TssPuls = (int)tssPulsTall;

                    score.x = i;
                    //if (score.Score != 0 && score.TssPuls != 0 && score.TssWatt != 0)
                    //{
                        stats.Add(score);
                        //this.InsertSuffer(score);
                    //}
                    
                //}
            }
            return stats.ToArray();
        }

        //private async static Task<AthleteSummary> StravaTest()
        private async Task<List<Comment>> StravaTest()
        {
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            StaticAuthentication auth = new StaticAuthentication(user.StravaKey);
            //StaticAuthentication auth = new StaticAuthentication("72da1a028657d1d0a5c628c87373bebdf15151db");
            StravaClient client = new StravaClient(auth);

            //List<Comment> comments = await client.GetCommentsAsync("102162300");
            //Activity athlete = await client.GetActivityAsync("102162300");
            //Athlete athlete = await client.GetAthleteAsync("1985994");
            //AthleteSummary a = await client.Athletes.GetAthleteAsync();
            var ass = getAthleteSummary();
            List<Comment> comments = await client.Activities.GetCommentsAsync("447602106");
            //AthleteSummary a = await client.Athletes.GetAthleteAsync(ass.Id.ToString());
            return comments;
        }
    }

    public static class EpochTimeExtensions
    {
        /// <summary>
        /// Converts the given date value to epoch time.
        /// </summary>
        public static long ToEpochTime(this DateTime dateTime)
        {
            var date = dateTime.ToUniversalTime();
            var ticks = date.Ticks - new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).Ticks;
            var ts = ticks / TimeSpan.TicksPerSecond;
            return ts;
        }

        /// <summary>
        /// Converts the given date value to epoch time.
        /// </summary>
        public static long ToEpochTime(this DateTimeOffset dateTime)
        {
            var date = dateTime.ToUniversalTime();
            var ticks = date.Ticks - new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero).Ticks;
            var ts = ticks / TimeSpan.TicksPerSecond;
            return ts;
        }

        /// <summary>
        /// Converts the given epoch time to a <see cref="DateTime"/> with <see cref="DateTimeKind.Utc"/> kind.
        /// </summary>
        public static DateTime ToDateTimeFromEpoch(this long intDate)
        {
            var timeInTicks = intDate * TimeSpan.TicksPerSecond;
            return new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc).AddTicks(timeInTicks);
        }

        /// <summary>
        /// Converts the given epoch time to a UTC <see cref="DateTimeOffset"/>.
        /// </summary>
        public static DateTimeOffset ToDateTimeOffsetFromEpoch(this long intDate)
        {
            var timeInTicks = intDate * TimeSpan.TicksPerSecond;
            return new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero).AddTicks(timeInTicks);
        }
    }
}

Stravaix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>StravaixRight</title>
    <link rel="icon" type="image/png" href="img/favicon.png">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-favicon.png">
    @Styles.Render("~/dist/libs/bootstrap/css/bootstrap.min.css")
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    @Styles.Render("~/dist/libs/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/dist/libs/jquery.scrollbar/jquery.scrollbar.css")
    @Styles.Render("~/dist/libs/morris.js/morris.css")
    @Styles.Render("~/dist/css/right.css")
    @Styles.Render("~/dist/css/demo.css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/modernizr")
    <script>
        /* yeah we need this empty stylesheet here. It's cool chrome & chromium fix
           chrome fix https://code.google.com/p/chromium/issues/detail?id=167083
                      https://code.google.com/p/chromium/issues/detail?id=332189
        */
    </script>
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">*@
    
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <script src="~/dist/libs/jquery/jquery.min.js"></script>
    <script src="~/dist/libs/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/dist/libs/jquery.scrollbar/jquery.scrollbar.min.js"></script>
    <script src="~/dist/libs/bootstrap-tabdrop/bootstrap-tabdrop.min.js"></script>
    <script src="~/dist/js/main.js"></script>
    <script src="~/dist/js/demo.js"></script>
</head>
<body class="solid_dark">
    <div class="wrapper">
        <nav class="navbar navbar-static-top header-navbar">
            <div class="container-fluid">
                <div class="header-navbar-mobile">
                    <div class="header-navbar-mobile__menu">
                        <button type="button" class="btn"><i class="fa fa-bars"></i></button>
                    </div>
                    <div class="header-navbar-mobile__title"><span>Blank</span></div>
                    <div class="header-navbar-mobile__settings dropdown">
                        <a href="" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="btn dropdown-toggle"><i class="fa fa-power-off"></i></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#">Log Out</a></li>
                        </ul>
                    </div>
                </div>
                <div class="navbar-header">
                    <a href="#" class="navbar-brand">
                        <div class="logo text-nowrap">
                            <div class="logo__img"><i class="fa fa-chevron-right"></i></div><span class="logo__text">Right</span>
                        </div>
                    </a>
                </div>
                <div id="navbar-top" class="navbar-collapse collapse topnavbar">
                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="./"><span>Dashboard</span></a></li>
                        <li class="dropdown active">
                            <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><span>Pages&nbsp;<i class="caret"></i></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                <li><a href="orders.html"><span>Orders</span></a></li>
                                <li><a href="users.html"><span>Users</span></a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="login.html">Login</a></li>
                                <li class="active"><a href="blank.html">Blank</a></li>
                            </ul>
                        </li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                    <ul class="userbar nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" class="userbar__settings dropdown-toggle"><i class="fa fa-power-off"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Log Out</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="dashboard">
            <div class="sidebar">
                <div class="scrollable scrollbar-macosx">
                    <div class="sidebar__cont">
                        <ul class="nav nav-sidebar">
                            <li><span class="sidebar__title">Pages</span></li>
                            <li><a href="./"><i class="fa fa-fw fa-star"></i><span>Dashboard</span></a></li>
                            <li><a href="products.html"><i class="fa fa-fw fa-cube"></i><span>Products</span></a></li>
                            <li><a href="orders.html"><i class="fa fa-fw fa-truck"></i><i class="badge pull-right">2</i><span>Orders</span></a></li>
                            <li>@Html.ActionLink("Sufferscore", "Index", "Suffer")</li>
                            <li class="active opened">
                                <a href="#"><i class="fa fa-fw fa-folder-o"></i><span>Other</span><i class="fa fa-fw fa-angle-right arrow"></i></a>
                                <ul class="nav sidebar__second-level collapse in">
                                    <li class="active"><a href="blank.html">Blank</a></li>
                                    <li><a href="login.html">Login</a></li>
                                </ul>
                            </li>
                            <li><span class="sidebar__title">Template</span></li>
                            <li>
                                <a href="#"><i class="fa fa-fw fa-th-large"></i><span>UI Elements</span><i class="fa fa-fw fa-angle-right arrow"></i></a>
                                <ul class="nav sidebar__second-level collapse">
                                    <li><a href="general.html">General</a></li>
                                    <li><a href="panels.html">Panels</a></li>
                                    <li><a href="tabs.html">Tabs</a></li>
                                    <li><a href="modals.html">Modals</a></li>
                                    <li><a href="buttons.html">Buttons</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-fw fa-clone"></i><span>Forms</span><i class="fa fa-fw fa-angle-right arrow"></i></a>
                                <ul class="nav sidebar__second-level collapse">
                                    <li><a href="controls.html">Controls</a></li>
                                    <li><a href="validation.html">Validation</a></li>
                                    <li><a href="texteditor.html">Text Editor</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-fw fa-table"></i><span>Tables</span><i class="fa fa-fw fa-angle-right arrow"></i></a>
                                <ul class="nav sidebar__second-level collapse">
                                    <li><a href="table_static.html">Static</a></li>
                                    <li><a href="table_sortable.html">Sortable</a></li>
                                    <li><a href="table_data.html">DataTable</a></li>
                                </ul>
                            </li>
                            <li><a href="charts.html"><i class="fa fa-fw fa-pie-chart"></i><span>Charts</span></a></li>
                        </ul>
                    </div>
                    <div class="sidebar__logo"></div>
                </div>
            </div>
            <div class="main">
                <div class="scrollable scrollbar-macosx">
                    <div class="main__cont">
                        <div class="main-heading">
                            <div class="main-title">
                                <ol class="breadcrumb">
                                    <li class="active">Blank</li>
                                </ol>
                            </div>
                            <div class="main-filter">
                                <form class="main-filter__search">
                                    <div class="input-group">
                                        <input type="text" placeholder="Search..." class="form-control"><span class="input-group-btn">
                                            <button type="button" class="btn btn-default">
                                                <div class="fa fa-search"></div>
                                            </button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="container-fluid half-padding">
                            <div class="template template__blank">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="panel panel-danger">
                                            <div class="panel-heading">
                                                <h3 class="panel-title">Blank Page</h3>
                                            </div>
                                            <div class="panel-body">
                                                @RenderBody()
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="demo">
        <div class="demo__ico"></div>
        <div class="demo__cont">
            <div class="demo__settings">
                <div class="demo__group">
                    <div class="demo__label">Color theme:</div>
                    <div class="demo__themes">
                        <div data-theme="solid_dark" title="Dark" class="demo__theme demo__theme_active demo__theme_dark"></div>
                        <div data-theme="transparent_lilac" title="Lilac" class="demo__theme demo__theme_lilac"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Stravaix/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>